services:

  backend: &backend
    image: "langflowai/langflow-backend:latest"
    env_file:
      - .env
    healthcheck:
      test: "exit 0"
    deploy:
      labels:
        - traefik.enable=true
        - traefik.constraint-label-stack=${TRAEFIK_TAG?Variable not set}
        - traefik.http.routers.${STACK_NAME?Variable not set}-backend-http.rule=PathPrefix(`/api/v1`) || PathPrefix(`/docs`) || PathPrefix(`/health`)
        - traefik.http.services.${STACK_NAME?Variable not set}-backend.loadbalancer.server.port=7860

networks:
  dokploy-network:
    external: true
  traefik-public:
    # Allow setting it to false for testing
    external: false # ${TRAEFIK_PUBLIC_NETWORK_IS_EXTERNAL-true}
